### ISSUE TITLE
[RFE] implement update feature for atomic hosts

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#93] opened 2015-06-07 13:35 UTC
`update: true` will result in a `yum update` inside the box, this is pretty nice, if you run RHEL/CentOS/Fedora Server, if is useless on Atomic Hosts.

implement `update` so that an Atomic Host is identified and a `atomic host upgrade` is called.

**Comment by purpleidea** [comment] 2015-06-08 19:03
duplicate of https://github.com/purpleidea/oh-my-vagrant/issues/75

**Closed by purpleidea** 2015-06-08 19:03 UTC

**Comment by goern** [comment] 2015-06-09 12:32
this is not is duplicate but a refinement to track an individual feature of #75 more easily
