### ISSUE TITLE
atomic host upgrad leaves box unusable

### ISSUE THREAD

**Issue by goern** [purpleidea/oh-my-vagrant#90] opened 2015-05-27 13:58 UTC
bringing up an (RHEL) Atomic Host and performing `atomic host upgrade` leaves the host unusable. Network interface configuration seems to be screwed up..

**Comment by goern** [comment] 2015-05-27 14:55
some more background, libvirt has created the atomic host with
```
...
   <interface type='network'>
      <mac address='52:54:00:43:b6:42'/>
      <source network='vagrant-libvirt'/>
      <target dev='vnet2'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
    <interface type='network'>
      <mac address='52:54:00:ce:a7:c7'/>
      <source network='node-'/>
      <target dev='vnet4'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
...
```

network configuration before upgrade is:
```
[vagrant@node-1 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:43:b6:42 brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.49/24 brd 192.168.121.255 scope global dynamic eth0
       valid_lft 3501sec preferred_lft 3501sec
    inet 192.168.91.100/24 brd 192.168.91.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe43:b642/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:ce:a7:c7 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:fece:a7c7/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

192.168.91/24 is network `node-` and 192.168.121/24 is vagrant-libvirt.

**Comment by goern** [comment] 2015-05-27 15:20
after `atomic host upgrade` networking is a little different:
```
[vagrant@node-1 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:43:b6:42 brd ff:ff:ff:ff:ff:ff
    inet 192.168.91.100/24 brd 192.168.91.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe43:b642/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:ce:a7:c7 brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

```
[vagrant@node-1 ~]$ sudo atomic host status
  TIMESTAMP (UTC)         VERSION     ID             OSNAME               REFSPEC                                                        
* 2015-05-07 19:00:48     7.1.2       203dd666d3     rhel-atomic-host     rhel-atomic-host-ostree:rhel-atomic-host/7/x86_64/standard     
```

**Comment by LalatenduMohanty** [comment] 2015-05-27 16:39
Not sure , is it related to https://bugzilla.redhat.com/show_bug.cgi?id=1221006

**Comment by purpleidea** [comment] 2015-05-27 18:31
On Wed, May 27, 2015 at 12:39 PM, Lalatendu Mohanty <
notifications@github.com> wrote:

> Not sure , is it related to
> https://bugzilla.redhat.com/show_bug.cgi?id=1221006
>


Agreed!

**Comment by purpleidea** [comment] 2015-07-02 10:54
Fixed in F22 package. Reopen if the root cause was different.

**Closed by purpleidea** 2015-07-02 10:54 UTC
